import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  'https://zelympuwxfygdwhyiqgv.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplbHltcHV3eGZ5Z2R3aHlpcWd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgzNTI3NTcsImV4cCI6MjA5MzkyODc1N30.nj-TAeYFhP8F-jBRDWTHcRSjHzj33egTec8K79hqIaQ'
)

const properties = [
  {
    nama: 'Rumah Minimalis Modern Kemang',
    deskripsi: 'Rumah 2 lantai desain minimalis modern di kawasan premium Kemang. Dekat pusat perbelanjaan dan restoran. Lingkungan tenang dan aman dengan keamanan 24 jam.',
    harga: 4500000000,
    tipe: 'rumah',
    kota_wilayah: 'Jakarta Selatan',
    kecamatan: 'Kemang',
    alamat: 'Jl. Kemang Raya No. 45',
    kamar_tidur: 4,
    kamar_mandi: 3,
    luas_tanah: 300,
    luas_bangunan: 250,
    lantai: 2,
    garasi: 2,
    sertifikat: 'SHM',
    kondisi: 'Bagus',
    fasilitas: ['Kolam Renang', 'Parkir', 'Keamanan 24 Jam', 'AC', 'CCTV'],
    foto_urls: ['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800'],
    lat: -6.2607,
    lng: 106.8133,
    status: 'aktif',
  },
  {
    nama: 'Apartemen Mewah Sudirman CBD',
    deskripsi: 'Apartemen studio premium di jantung kawasan bisnis Sudirman. View gedung pencakar langit yang spektakuler. Fasilitas lengkap bintang 5.',
    harga: 1800000000,
    tipe: 'apartemen',
    kota_wilayah: 'Jakarta Pusat',
    kecamatan: 'Tanah Abang',
    alamat: 'Jl. Jend. Sudirman No. 10',
    kamar_tidur: 1,
    kamar_mandi: 1,
    luas_tanah: 0,
    luas_bangunan: 45,
    lantai: 1,
    garasi: 1,
    sertifikat: 'SHGB',
    kondisi: 'Bagus',
    fasilitas: ['Gym', 'Kolam Renang', 'Keamanan 24 Jam', 'Lift', 'AC', 'CCTV'],
    foto_urls: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800'],
    lat: -6.2088,
    lng: 106.8229,
    status: 'aktif',
  },
  {
    nama: 'Rumah Cluster Elite Pondok Indah',
    deskripsi: 'Hunian eksklusif dalam cluster tertutup di Pondok Indah. Area perumahan terbaik Jakarta dengan lingkungan hijau dan fasilitas premium.',
    harga: 12000000000,
    tipe: 'rumah',
    kota_wilayah: 'Jakarta Selatan',
    kecamatan: 'Pondok Indah',
    alamat: 'Jl. Metro Pondok Indah No. 22',
    kamar_tidur: 5,
    kamar_mandi: 4,
    luas_tanah: 600,
    luas_bangunan: 500,
    lantai: 3,
    garasi: 3,
    sertifikat: 'SHM',
    kondisi: 'Bagus',
    fasilitas: ['Kolam Renang', 'Gym', 'Taman', 'Parkir', 'Keamanan 24 Jam', 'AC', 'CCTV'],
    foto_urls: ['https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800'],
    lat: -6.2700,
    lng: 106.7899,
    status: 'aktif',
  },
  {
    nama: 'Ruko Strategis Pluit',
    deskripsi: 'Ruko 3 lantai di lokasi bisnis ramai Pluit. Cocok untuk kantor, showroom, atau toko. Akses mudah ke tol dan bandara.',
    harga: 6500000000,
    tipe: 'ruko',
    kota_wilayah: 'Jakarta Utara',
    kecamatan: 'Pluit',
    alamat: 'Jl. Pluit Raya No. 78',
    kamar_tidur: 0,
    kamar_mandi: 2,
    luas_tanah: 150,
    luas_bangunan: 400,
    lantai: 3,
    garasi: 2,
    sertifikat: 'SHM',
    kondisi: 'Bagus',
    fasilitas: ['Parkir', 'CCTV', 'AC'],
    foto_urls: ['https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800'],
    lat: -6.1213,
    lng: 106.7897,
    status: 'aktif',
  },
  {
    nama: 'Apartemen 2BR Green Lake Sunter',
    deskripsi: 'Apartemen 2 kamar tidur dengan view danau yang memukau. Lingkungan asri dan hijau di Sunter. Fasilitas lengkap untuk keluarga.',
    harga: 950000000,
    tipe: 'apartemen',
    kota_wilayah: 'Jakarta Utara',
    kecamatan: 'Sunter',
    alamat: 'Jl. Danau Sunter Barat No. 5',
    kamar_tidur: 2,
    kamar_mandi: 1,
    luas_tanah: 0,
    luas_bangunan: 68,
    lantai: 1,
    garasi: 1,
    sertifikat: 'SHGB',
    kondisi: 'Bagus',
    fasilitas: ['Kolam Renang', 'Taman', 'Keamanan 24 Jam', 'Lift', 'AC'],
    foto_urls: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800'],
    lat: -6.1500,
    lng: 106.8700,
    status: 'aktif',
  },
  {
    nama: 'Rumah Asri Duren Sawit',
    deskripsi: 'Rumah keluarga nyaman di Duren Sawit Jakarta Timur. Lingkungan perumahan yang tenang, dekat sekolah dan pasar.',
    harga: 2200000000,
    tipe: 'rumah',
    kota_wilayah: 'Jakarta Timur',
    kecamatan: 'Duren Sawit',
    alamat: 'Jl. Duren Sawit Raya No. 15',
    kamar_tidur: 3,
    kamar_mandi: 2,
    luas_tanah: 200,
    luas_bangunan: 160,
    lantai: 2,
    garasi: 1,
    sertifikat: 'SHM',
    kondisi: 'Bagus',
    fasilitas: ['Taman', 'Parkir', 'AC'],
    foto_urls: ['https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800'],
    lat: -6.2200,
    lng: 106.9100,
    status: 'aktif',
  },
  {
    nama: 'Tanah Kavling Cengkareng',
    deskripsi: 'Tanah kavling strategis di Cengkareng, dekat Bandara Soekarno-Hatta. Cocok untuk investasi properti jangka panjang.',
    harga: 3000000000,
    tipe: 'tanah',
    kota_wilayah: 'Jakarta Barat',
    kecamatan: 'Cengkareng',
    alamat: 'Jl. Raya Cengkareng No. 200',
    kamar_tidur: 0,
    kamar_mandi: 0,
    luas_tanah: 500,
    luas_bangunan: 0,
    lantai: 0,
    garasi: 0,
    sertifikat: 'SHM',
    kondisi: 'Bagus',
    fasilitas: [],
    foto_urls: ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800'],
    lat: -6.1439,
    lng: 106.7394,
    status: 'aktif',
  },
  {
    nama: 'Rumah Minimalis Serpong Style',
    deskripsi: 'Rumah modern bergaya industrial di kawasan Kebon Jeruk. Dekat pusat perbelanjaan Ciputra Mall dan akses tol.',
    harga: 3800000000,
    tipe: 'rumah',
    kota_wilayah: 'Jakarta Barat',
    kecamatan: 'Kebon Jeruk',
    alamat: 'Jl. Kebon Jeruk Raya No. 88',
    kamar_tidur: 3,
    kamar_mandi: 2,
    luas_tanah: 180,
    luas_bangunan: 150,
    lantai: 2,
    garasi: 2,
    sertifikat: 'SHM',
    kondisi: 'Bagus',
    fasilitas: ['Parkir', 'Keamanan 24 Jam', 'AC', 'CCTV'],
    foto_urls: ['https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800'],
    lat: -6.1977,
    lng: 106.7632,
    status: 'aktif',
  },
  {
    nama: 'Apartemen Studio Thamrin City',
    deskripsi: 'Studio apartment modern di Thamrin, pusat kota Jakarta. Ideal untuk profesional muda yang ingin tinggal di tengah kota.',
    harga: 750000000,
    tipe: 'apartemen',
    kota_wilayah: 'Jakarta Pusat',
    kecamatan: 'Menteng',
    alamat: 'Jl. Thamrin Blvd No. 3',
    kamar_tidur: 1,
    kamar_mandi: 1,
    luas_tanah: 0,
    luas_bangunan: 28,
    lantai: 1,
    garasi: 0,
    sertifikat: 'SHGB',
    kondisi: 'Bagus',
    fasilitas: ['Gym', 'Kolam Renang', 'Lift', 'Keamanan 24 Jam', 'AC'],
    foto_urls: ['https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800'],
    lat: -6.1944,
    lng: 106.8229,
    status: 'aktif',
  },
  {
    nama: 'Villa Exclusive Kuningan',
    deskripsi: 'Villa mewah bergaya resort di kawasan diplomatik Kuningan. Kolam renang private, taman luas, dan privasi tinggi.',
    harga: 18000000000,
    tipe: 'villa',
    kota_wilayah: 'Jakarta Selatan',
    kecamatan: 'Kuningan',
    alamat: 'Jl. Kuningan Mulia No. 9',
    kamar_tidur: 6,
    kamar_mandi: 5,
    luas_tanah: 1000,
    luas_bangunan: 700,
    lantai: 2,
    garasi: 4,
    sertifikat: 'SHM',
    kondisi: 'Bagus',
    fasilitas: ['Kolam Renang', 'Gym', 'Taman', 'Parkir', 'Keamanan 24 Jam', 'AC', 'CCTV', 'Lift'],
    foto_urls: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800'],
    lat: -6.2297,
    lng: 106.8311,
    status: 'aktif',
  },
  {
    nama: 'Rumah Hook Perumahan Cempaka Putih',
    deskripsi: 'Rumah posisi hook di perumahan Cempaka Putih. Halaman luas, cocok untuk keluarga besar. Dekat RS dan sekolah favorit.',
    harga: 2800000000,
    tipe: 'rumah',
    kota_wilayah: 'Jakarta Pusat',
    kecamatan: 'Cempaka Putih',
    alamat: 'Jl. Cempaka Putih Tengah No. 33',
    kamar_tidur: 4,
    kamar_mandi: 3,
    luas_tanah: 250,
    luas_bangunan: 200,
    lantai: 2,
    garasi: 2,
    sertifikat: 'SHM',
    kondisi: 'Bagus',
    fasilitas: ['Taman', 'Parkir', 'Keamanan 24 Jam', 'AC'],
    foto_urls: ['https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800'],
    lat: -6.1720,
    lng: 106.8658,
    status: 'aktif',
  },
  {
    nama: 'Ruko 4 Lantai Glodok',
    deskripsi: 'Ruko premium 4 lantai di kawasan bisnis Glodok. Cocok untuk usaha perdagangan, kantor, atau gudang. Lokasi strategis dekat Kota Tua.',
    harga: 9500000000,
    tipe: 'ruko',
    kota_wilayah: 'Jakarta Barat',
    kecamatan: 'Taman Sari',
    alamat: 'Jl. Hayam Wuruk No. 120',
    kamar_tidur: 0,
    kamar_mandi: 4,
    luas_tanah: 200,
    luas_bangunan: 700,
    lantai: 4,
    garasi: 2,
    sertifikat: 'SHM',
    kondisi: 'Bagus',
    fasilitas: ['Lift', 'Parkir', 'AC', 'CCTV'],
    foto_urls: ['https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=800'],
    lat: -6.1444,
    lng: 106.8133,
    status: 'aktif',
  },
]

async function seed() {
  console.log('🚀 Memulai seed data properti...')

  // Cek koneksi
  const { data: test, error: testErr } = await supabase.from('properties').select('id').limit(1)
  if (testErr) {
    console.error('❌ Gagal koneksi ke Supabase:', testErr.message)
    console.log('💡 Pastikan tabel "properties" sudah ada di Supabase.')
    process.exit(1)
  }

  // Cek apakah sudah ada data
  const { count } = await supabase.from('properties').select('*', { count: 'exact', head: true }).eq('status', 'aktif')
  if (count > 0) {
    console.log(`ℹ️  Database sudah memiliki ${count} properti. Melewati seed.`)
    console.log('✅ Seed selesai (data sudah ada).')
    process.exit(0)
  }

  // Insert data
  const { data, error } = await supabase.from('properties').insert(properties).select()
  if (error) {
    console.error('❌ Gagal insert data:', error.message)
    console.log('Detail:', JSON.stringify(error, null, 2))
    process.exit(1)
  }

  console.log(`✅ Berhasil memasukkan ${data.length} properti ke database!`)
  data.forEach(p => console.log(`   ▸ ${p.nama} (${p.kota_wilayah})`))
}

seed()
